version: '3.0'

services:
  admin-tools-api:
    container_name: admin-tools-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/admin_tools?serverTimezone=GMT-6
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=ronLsnta123.
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
