server.port=8090
logging.level.org.springframework.data.jpa=DEBUG
spring.jpa.properties.hibernate.show_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/admin_tools?serverTimezone=GMT-6
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/admin_tools
spring.datasource.url=jdbc:mysql://localhost:3306/PacRoc_backup
#spring.datasource.url=jdbc:mysql://192.168.10.102:3306/admin_tools
spring.datasource.username=root
spring.datasource.password=Jdmm123.
#spring.datasource.password=ronLsnta123.

# Habilitar logging de SQL
spring.jpa.show-sql=true

# Habilitar logging detallado de SQL
spring.jpa.properties.hibernate.format_sql=true
